name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache maven modules
      uses: actions/cache@v1
      with:
        path: test
        key: ${{ runner.OS }}-build-cache-key
    - name: Build with Maven
      run: mvn clean install --file complete/pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: vt-demo
        # Directory containing files to upload
        path: complete/target
    - name: 'Run Azure webapp deploy action using publish profile credential'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: vt-demo
        package: complete/target/gs-spring-boot-0.1.0.war
        publish-profile: ${{ secrets.azurePublishProfile }}
